.\" man page create by R# package system.
.TH OLLAMA 1 2000-Jan "add_tool" "add_tool"
.SH NAME
add_tool \- 
.SH SYNOPSIS
\fIadd_tool(\fBmodel\fR as <generic> Ollama, 
\fBname\fR as string, 
\fBdesc\fR as string, 
\fBrequires\fR as any, 
\fBargs\fR as list = \fB<NULL>\fR, 
\fBfcall\fR as <closure> RFunction = \fB<NULL>\fR, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
ollama
.SH FILES
.PP
Agent.dll
.PP
