.\" man page create by R# package system.
.TH OLLAMA 1 2000-Jan "deepseek_chat" "deepseek_chat"
.SH NAME
deepseek_chat \- 
.SH SYNOPSIS
\fIdeepseek_chat(\fBmessage\fR as string, 
\fBollama_serve\fR as string = "127.0.0.1:11434", 
\fBmodel\fR as string = "deepseek-r1:671b");\fR
.SH SEE ALSO
ollama
.SH FILES
.PP
Agent.dll
.PP
