.\" man page create by R# package system.
.TH CHATGLM 1 2000-Jan "batch_transaltion" "batch_transaltion"
.SH NAME
batch_transaltion \- 
.SH SYNOPSIS
\fIbatch_transaltion(\fBcontent\fR as <generic> dataframe, 
\fBprompt_text\fR as string = "你是一个从英文到中文的语言翻译器", 
\fBadd_explains\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
chatglm
.SH FILES
.PP
Agent.dll
.PP
