.\" man page create by R# package system.
.TH CHATGLM 1 2000-Jan "parse_batch_output" "parse_batch_output"
.SH NAME
parse_batch_output \- 
.SH SYNOPSIS
\fIparse_batch_output(\fBfile\fR as any, 
\fBparse_annotation\fR as boolean = TRUE, 
[\fB<Environment>\fR]);\fR
.SH SEE ALSO
chatglm
.SH FILES
.PP
Agent.dll
.PP
